### ISSUE TITLE
Use dynamic variables

### ISSUE THREAD

**Issue by bigperson** [InteractionDesignFoundation/nova-unlayer-field#1]
Hey. Thanks for your package.
I would like to know if it is possible to somehow use my variable values.

For example, routes, data from a model, etc.

**Comment by lptn** [comment]
@bigperson 
Hey. Yes, it's possible, you can use then in a context of custom tool: https://docs.unlayer.com/docs/custom-tools

+ Nunjucks syntax in your template: `{{ data.your_variable_name }}`

Also please check https://docs.unlayer.com/docs/merge-tags and  https://docs.unlayer.com/docs/design-tags probably they can also solve what you need
