### ISSUE TITLE
'locale' config option is not optional

### ISSUE THREAD

**Issue by bredmor** [InteractionDesignFoundation/nova-unlayer-field#6]
The README says this option is optional, however failing to specify it causes a javascript error from `vendor.js` - `locale is not defined`.

**Comment by phuclh** [comment]
I have the same issue.

**Comment by lptn** [comment]
@bredmor 
@phuclh 
I couldn't reproduce it unfortunately. Can you please share a minimal config that causes this error?

**Comment by lptn** [comment]
should be fixed within version [0.2.2](https://github.com/InteractionDesignFoundation/nova-unlayer-field/releases/tag/0.2.2)
