### ISSUE TITLE
Error while installing package

### ISSUE THREAD

**Issue by felloz** [InteractionDesignFoundation/nova-unlayer-field#7]
...

**Comment by felloz** [comment]
I use composer require and get  this error:

`@php artisan package:discover --ansi

   Error

  Class 'Laravel\Nova\Nova' not found

  at E:\Laravel\unlayer-laravel\vendor\idf\nova-unlayer-field\src\ServiceProvider.php:13
     9| {
    10|     /** @inheritDoc */
    11|     public function boot(): void
    12|     {
  > 13|         Nova::serving(function () {
    14|             Nova::script('nova-unlayer-field', __DIR__.'/../dist/js/field.js');
    15|         });
    16|
    17|         $this->publishes([

  1   E:\Laravel\unlayer-laravel\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
      IDF\NovaUnlayerField\ServiceProvider::boot()

  2   E:\Laravel\unlayer-laravel\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:37
      call_user_func_array([])
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
`

**Comment by lptn** [comment]
Hello @felloz 
You need to install Nova before installing this package

**Comment by felloz** [comment]
Laravel Nova its a payed package right?

**Comment by pawelmysior** [comment]
@felloz yes.
